### PR TITLE
[FIX] account_invoice_tax: Fix in _prepare_tax_totals super method

### PR DESCRIPTION
**Pull request by mem-adhoc**
Task: 34430

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/174).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-invoicing#175

**Pull request closed without merging**
