### PR TITLE
[FW][MIG] Upgrade account_invoice_control to 16.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-invoicing#163

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/176).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @ica-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by jjscarafia** [comment]
siguiendo esto en task 37625

**Pull request closed without merging**
