### PR TITLE
[MIG] account_invoice_commission: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-invoicing/pull/118).

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Review by PabloPaezSheridan — APPROVED** [review]

**Comment by PabloPaezSheridan** [comment]
r+

**Comment by PabloPaezSheridan** [comment]
@roboadhoc r+

**Pull request closed without merging**
