### PR TITLE
[FW][MIG] account_invoice_line_number: migration to 16.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-invoicing#197

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/198).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by cav-adhoc** [comment]
A migrar según demanda en v17

**Pull request closed without merging**
