### PR TITLE
[MIG] website_sale_account_invoice_commission: Migration to 15.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-invoicing/pull/134).

**Comment by jjscarafia** [comment]
@roboadhoc rebase-ff

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Pull request closed without merging**
