### PR TITLE
[MIG] account_invoice_tax/: Migration to 16.0

### PR DESCRIPTION
**Pull request by ica-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-invoicing/pull/144).

**Review by maq-adhoc — APPROVED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc. I'm afraid I can't do that.

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Pull request closed without merging**
