### PR TITLE
[IMP] account_invoice_commission: Make optional hide field commission_amount on invoice form

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/199).

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by feg-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @feg-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
