### PR TITLE
[FIX] account_background_post: set background_post to false when copy invoice

### PR DESCRIPTION
**Pull request by cav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/185).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
