### PR TITLE
[FW][FIX] account_invoice_commission: improve performance

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-invoicing#132

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-invoicing/pull/133).

**Comment by fw-bot-adhoc** [comment]
Ping @augusto-weiss, @jjscarafia cherrypicking of pull request ingadhoc/account-invoicing#132 failed.

stdout:
```
Auto-merging account_invoice_commission/models/account_move.py
CONFLICT (content): Merge conflict in account_invoice_commission/models/account_move.py

```

stderr:
```
12:41:59.211820 git.c:439               trace: built-in: git cherry-pick ed19cbd30c76374f9dd7abb31d603e0274b2a471
error: could not apply ed19cbd3... [FIX] account_invoice_commission: improve performance
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by augusto-weiss** [comment]
@nicomacr 
Nico! listo para mezclar! gracias!!

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
