### PR TITLE
[FW][IMP] account_invoice_commission: Make optional hide field commission_amount on invoice form

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-invoicing#199

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-invoicing/pull/200).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @cav-adhoc cherrypicking of pull request ingadhoc/account-invoicing#199 failed.

stdout:
```
Auto-merging account_invoice_commission/views/account_move_view.xml
CONFLICT (content): Merge conflict in account_invoice_commission/views/account_move_view.xml
Auto-merging account_invoice_commission/__manifest__.py
CONFLICT (content): Merge conflict in account_invoice_commission/__manifest__.py

```

stderr:
```
14:19:06.321174 git.c:444               trace: built-in: git cherry-pick 15dca50cf762939f9e901bfa2440ed12c99feee6
error: could not apply 15dca50c... [IMP] account_invoice_commission: Make optional hide field commission_amount on invoice form
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
